export interface Metro {
  slug: string;
  name: string;
  state: string;
  states: string[];
  cities: string[];
  description: string;
}

export const TOP_METROS: Metro[] = [
  {
    slug: 'new-york',
    name: 'New York City',
    state: 'NY',
    states: ['NY', 'NJ', 'CT'],
    cities: ['New York', 'Brooklyn', 'Queens', 'Bronx', 'Staten Island', 'Newark', 'Jersey City', 'Yonkers', 'White Plains', 'Stamford', 'Hoboken', 'Paterson', 'Elizabeth', 'New Rochelle', 'Mount Vernon'],
    description: 'The New York City metro area hosts dozens of Pokemon and trading card shows every month across NYC, northern New Jersey, and southern Connecticut.',
  },
  {
    slug: 'los-angeles',
    name: 'Los Angeles',
    state: 'CA',
    states: ['CA'],
    cities: ['Los Angeles', 'Long Beach', 'Anaheim', 'Santa Ana', 'Glendale', 'Pasadena', 'Torrance', 'Pomona', 'Burbank', 'Inglewood', 'Ontario', 'Downey', 'Whittier', 'Fullerton', 'Costa Mesa'],
    description: 'The Los Angeles metro area is one of the largest markets for Pokemon card shows, with events spanning LA County and Orange County every weekend.',
  },
  {
    slug: 'chicago',
    name: 'Chicago',
    state: 'IL',
    states: ['IL', 'IN', 'WI'],
    cities: ['Chicago', 'Aurora', 'Naperville', 'Joliet', 'Elgin', 'Schaumburg', 'Evanston', 'Arlington Heights', 'Tinley Park', 'Rosemont', 'Gary', 'Hammond', 'Kenosha'],
    description: 'The Chicago metro area features a thriving card show scene across Chicagoland, northwest Indiana, and southeastern Wisconsin.',
  },
  {
    slug: 'houston',
    name: 'Houston',
    state: 'TX',
    states: ['TX'],
    cities: ['Houston', 'Pasadena', 'Sugar Land', 'Pearland', 'League City', 'Baytown', 'Missouri City', 'Conroe', 'Spring', 'Katy', 'Humble', 'Cypress', 'The Woodlands'],
    description: 'The Houston metro area is a hub for Pokemon card shows and trading card events across the greater Houston region in southeast Texas.',
  },
  {
    slug: 'dallas-fort-worth',
    name: 'Dallas/Fort Worth',
    state: 'TX',
    states: ['TX'],
    cities: ['Dallas', 'Fort Worth', 'Arlington', 'Plano', 'Irving', 'Garland', 'Frisco', 'McKinney', 'Grand Prairie', 'Denton', 'Mesquite', 'Carrollton', 'Richardson', 'Allen', 'Lewisville'],
    description: 'The Dallas/Fort Worth metroplex is one of the most active card show regions in Texas, with regular Pokemon and trading card events across the DFW area.',
  },
  {
    slug: 'phoenix',
    name: 'Phoenix',
    state: 'AZ',
    states: ['AZ'],
    cities: ['Phoenix', 'Mesa', 'Chandler', 'Scottsdale', 'Glendale', 'Tempe', 'Gilbert', 'Peoria', 'Surprise', 'Goodyear', 'Avondale', 'Buckeye'],
    description: 'The Phoenix metro area offers year-round Pokemon card shows and trading card events throughout the Valley of the Sun.',
  },
  {
    slug: 'philadelphia',
    name: 'Philadelphia',
    state: 'PA',
    states: ['PA', 'NJ', 'DE'],
    cities: ['Philadelphia', 'Chester', 'Norristown', 'King of Prussia', 'Wilmington', 'Cherry Hill', 'Camden', 'Bensalem', 'Oaks', 'Conshohocken', 'Lansdale', 'Doylestown'],
    description: 'The Philadelphia metro area spans southeastern Pennsylvania, southern New Jersey, and northern Delaware, hosting regular card show events.',
  },
  {
    slug: 'san-antonio',
    name: 'San Antonio',
    state: 'TX',
    states: ['TX'],
    cities: ['San Antonio', 'New Braunfels', 'San Marcos', 'Schertz', 'Seguin', 'Cibolo', 'Universal City', 'Live Oak', 'Converse'],
    description: 'The San Antonio metro area features a growing Pokemon card show scene with events across south-central Texas.',
  },
  {
    slug: 'san-diego',
    name: 'San Diego',
    state: 'CA',
    states: ['CA'],
    cities: ['San Diego', 'Chula Vista', 'Oceanside', 'Escondido', 'Carlsbad', 'El Cajon', 'Vista', 'San Marcos', 'Encinitas', 'National City', 'La Mesa', 'Poway'],
    description: 'The San Diego metro area hosts Pokemon card shows and trading card events year-round in America\'s Finest City and surrounding communities.',
  },
  {
    slug: 'san-francisco',
    name: 'San Francisco Bay Area',
    state: 'CA',
    states: ['CA'],
    cities: ['San Francisco', 'Oakland', 'Berkeley', 'Fremont', 'Hayward', 'Richmond', 'Daly City', 'San Mateo', 'Redwood City', 'Concord', 'Walnut Creek', 'Pleasanton', 'Santa Rosa', 'Vallejo'],
    description: 'The San Francisco Bay Area is a major hub for Pokemon card shows and trading card events, spanning San Francisco, the East Bay, and the Peninsula.',
  },
  {
    slug: 'miami',
    name: 'Miami/Fort Lauderdale',
    state: 'FL',
    states: ['FL'],
    cities: ['Miami', 'Fort Lauderdale', 'Hollywood', 'Hialeah', 'Pembroke Pines', 'Coral Springs', 'Miramar', 'Davie', 'Pompano Beach', 'Boca Raton', 'Deerfield Beach', 'Homestead', 'Miami Gardens', 'Sunrise', 'Plantation'],
    description: 'The Miami/Fort Lauderdale metro area features a vibrant Pokemon card show scene across South Florida, from Miami-Dade through Broward and Palm Beach counties.',
  },
  {
    slug: 'atlanta',
    name: 'Atlanta',
    state: 'GA',
    states: ['GA'],
    cities: ['Atlanta', 'Sandy Springs', 'Roswell', 'Johns Creek', 'Alpharetta', 'Marietta', 'Smyrna', 'Duluth', 'Lawrenceville', 'Kennesaw', 'Decatur', 'Peachtree City', 'Woodstock', 'Canton', 'Douglasville'],
    description: 'The Atlanta metro area is the Southeast\'s largest market for Pokemon card shows, with events across the greater Atlanta region.',
  },
  {
    slug: 'boston',
    name: 'Boston',
    state: 'MA',
    states: ['MA', 'NH', 'RI'],
    cities: ['Boston', 'Cambridge', 'Quincy', 'Brockton', 'Worcester', 'Lowell', 'Lynn', 'Somerville', 'Framingham', 'Marlborough', 'Nashua', 'Providence', 'Warwick', 'Cranston'],
    description: 'The Boston metro area hosts regular Pokemon card shows and trading card events across eastern Massachusetts, southern New Hampshire, and Rhode Island.',
  },
  {
    slug: 'seattle',
    name: 'Seattle',
    state: 'WA',
    states: ['WA'],
    cities: ['Seattle', 'Tacoma', 'Bellevue', 'Kent', 'Everett', 'Renton', 'Federal Way', 'Kirkland', 'Auburn', 'Redmond', 'Lakewood', 'Puyallup', 'Lynnwood', 'Bothell'],
    description: 'The Seattle metro area is a thriving market for Pokemon card shows, with events throughout the Puget Sound region.',
  },
  {
    slug: 'denver',
    name: 'Denver',
    state: 'CO',
    states: ['CO'],
    cities: ['Denver', 'Aurora', 'Lakewood', 'Thornton', 'Arvada', 'Westminster', 'Centennial', 'Boulder', 'Longmont', 'Broomfield', 'Castle Rock', 'Parker', 'Littleton', 'Commerce City'],
    description: 'The Denver metro area is the Rocky Mountain region\'s top destination for Pokemon card shows and trading card events along the Front Range.',
  },
  {
    slug: 'detroit',
    name: 'Detroit',
    state: 'MI',
    states: ['MI'],
    cities: ['Detroit', 'Warren', 'Sterling Heights', 'Ann Arbor', 'Dearborn', 'Livonia', 'Troy', 'Southfield', 'Westland', 'Canton', 'Novi', 'Taylor', 'Pontiac', 'Royal Oak'],
    description: 'The Detroit metro area features regular Pokemon card shows and trading card events throughout southeast Michigan.',
  },
  {
    slug: 'minneapolis',
    name: 'Minneapolis/St. Paul',
    state: 'MN',
    states: ['MN', 'WI'],
    cities: ['Minneapolis', 'St. Paul', 'Bloomington', 'Brooklyn Park', 'Plymouth', 'Maple Grove', 'Woodbury', 'Eden Prairie', 'Lakeville', 'Burnsville', 'Eagan', 'Coon Rapids', 'Minnetonka'],
    description: 'The Minneapolis/St. Paul metro area hosts a strong Pokemon card show scene across the Twin Cities and surrounding suburbs.',
  },
  {
    slug: 'tampa',
    name: 'Tampa Bay',
    state: 'FL',
    states: ['FL'],
    cities: ['Tampa', 'St. Petersburg', 'Clearwater', 'Brandon', 'Largo', 'Lakeland', 'Palm Harbor', 'Plant City', 'Wesley Chapel', 'New Port Richey', 'Dunedin', 'Bradenton', 'Sarasota'],
    description: 'The Tampa Bay metro area offers frequent Pokemon card shows and trading card events across the greater Tampa, St. Petersburg, and Clearwater region.',
  },
  {
    slug: 'orlando',
    name: 'Orlando',
    state: 'FL',
    states: ['FL'],
    cities: ['Orlando', 'Kissimmee', 'Sanford', 'Altamonte Springs', 'Ocoee', 'Winter Park', 'Apopka', 'Clermont', 'Daytona Beach', 'Deltona', 'Oviedo', 'Lake Mary'],
    description: 'The Orlando metro area hosts regular Pokemon card shows and trading card events throughout Central Florida.',
  },
  {
    slug: 'las-vegas',
    name: 'Las Vegas',
    state: 'NV',
    states: ['NV'],
    cities: ['Las Vegas', 'Henderson', 'North Las Vegas', 'Summerlin', 'Enterprise', 'Spring Valley', 'Paradise', 'Sunrise Manor', 'Boulder City'],
    description: 'The Las Vegas metro area features Pokemon card shows and trading card events in the entertainment capital of the world.',
  },
  {
    slug: 'cleveland',
    name: 'Cleveland',
    state: 'OH',
    states: ['OH'],
    cities: ['Cleveland', 'Akron', 'Parma', 'Canton', 'Lakewood', 'Elyria', 'Mentor', 'Strongsville', 'Medina', 'Lorain', 'Cuyahoga Falls', 'North Olmsted', 'Fairlawn'],
    description: 'The Cleveland metro area hosts regular Pokemon card shows and trading card events throughout northeast Ohio.',
  },
  {
    slug: 'columbus',
    name: 'Columbus',
    state: 'OH',
    states: ['OH'],
    cities: ['Columbus', 'Dublin', 'Westerville', 'Grove City', 'Reynoldsburg', 'Hilliard', 'Gahanna', 'Upper Arlington', 'Delaware', 'Lancaster', 'Newark', 'Zanesville', 'Pickerington'],
    description: 'The Columbus metro area is a growing market for Pokemon card shows and trading card events in central Ohio.',
  },
  {
    slug: 'indianapolis',
    name: 'Indianapolis',
    state: 'IN',
    states: ['IN'],
    cities: ['Indianapolis', 'Carmel', 'Fishers', 'Noblesville', 'Greenwood', 'Lawrence', 'Avon', 'Plainfield', 'Brownsburg', 'Westfield', 'Zionsville', 'Anderson', 'Muncie'],
    description: 'The Indianapolis metro area features a strong card show scene with Pokemon and trading card events across central Indiana.',
  },
  {
    slug: 'charlotte',
    name: 'Charlotte',
    state: 'NC',
    states: ['NC', 'SC'],
    cities: ['Charlotte', 'Concord', 'Gastonia', 'Huntersville', 'Mooresville', 'Kannapolis', 'Matthews', 'Mint Hill', 'Monroe', 'Rock Hill', 'Fort Mill', 'Indian Trail'],
    description: 'The Charlotte metro area spans the Carolina border, hosting Pokemon card shows and trading card events across the greater Charlotte region.',
  },
  {
    slug: 'nashville',
    name: 'Nashville',
    state: 'TN',
    states: ['TN'],
    cities: ['Nashville', 'Murfreesboro', 'Franklin', 'Hendersonville', 'Lebanon', 'Gallatin', 'Mount Juliet', 'Smyrna', 'Brentwood', 'Spring Hill', 'Columbia', 'Clarksville'],
    description: 'The Nashville metro area hosts regular Pokemon card shows and trading card events throughout Middle Tennessee.',
  },
  {
    slug: 'portland',
    name: 'Portland',
    state: 'OR',
    states: ['OR', 'WA'],
    cities: ['Portland', 'Beaverton', 'Hillsboro', 'Gresham', 'Tigard', 'Lake Oswego', 'Tualatin', 'Oregon City', 'West Linn', 'Milwaukie', 'Vancouver', 'Camas'],
    description: 'The Portland metro area hosts Pokemon card shows and trading card events across the Portland-Vancouver metropolitan region in Oregon and Washington.',
  },
  {
    slug: 'kansas-city',
    name: 'Kansas City',
    state: 'MO',
    states: ['MO', 'KS'],
    cities: ['Kansas City', 'Overland Park', 'Olathe', 'Independence', 'Lee\'s Summit', 'Shawnee', 'Lenexa', 'Blue Springs', 'Leavenworth', 'Liberty', 'Gladstone', 'Raymore'],
    description: 'The Kansas City metro area spans the Missouri-Kansas border, hosting Pokemon card shows and trading card events across the KC region.',
  },
  {
    slug: 'sacramento',
    name: 'Sacramento',
    state: 'CA',
    states: ['CA'],
    cities: ['Sacramento', 'Elk Grove', 'Roseville', 'Folsom', 'Rancho Cordova', 'Citrus Heights', 'Rocklin', 'Davis', 'Woodland', 'West Sacramento', 'Lincoln', 'Auburn'],
    description: 'The Sacramento metro area features Pokemon card shows and trading card events throughout the Sacramento Valley and surrounding foothills.',
  },
  {
    slug: 'st-louis',
    name: 'St. Louis',
    state: 'MO',
    states: ['MO', 'IL'],
    cities: ['St. Louis', 'St. Charles', 'O\'Fallon', 'Florissant', 'Chesterfield', 'Kirkwood', 'Ballwin', 'Maryland Heights', 'Belleville', 'Edwardsville', 'Collinsville', 'Granite City'],
    description: 'The St. Louis metro area spans Missouri and Illinois, hosting Pokemon card shows and trading card events throughout the Gateway City region.',
  },
  {
    slug: 'san-jose',
    name: 'San Jose',
    state: 'CA',
    states: ['CA'],
    cities: ['San Jose', 'Santa Clara', 'Sunnyvale', 'Mountain View', 'Milpitas', 'Cupertino', 'Campbell', 'Los Gatos', 'Gilroy', 'Morgan Hill', 'Palo Alto', 'Santa Cruz'],
    description: 'The San Jose metro area in Silicon Valley hosts Pokemon card shows and trading card events across the South Bay and Santa Cruz County.',
  },
  {
    slug: 'austin',
    name: 'Austin',
    state: 'TX',
    states: ['TX'],
    cities: ['Austin', 'Round Rock', 'Cedar Park', 'Georgetown', 'Pflugerville', 'San Marcos', 'Kyle', 'Leander', 'Buda', 'Dripping Springs', 'Bastrop', 'Taylor'],
    description: 'The Austin metro area features a growing Pokemon card show scene with events throughout central Texas.',
  },
  {
    slug: 'pittsburgh',
    name: 'Pittsburgh',
    state: 'PA',
    states: ['PA', 'WV'],
    cities: ['Pittsburgh', 'Monroeville', 'Cranberry Township', 'Bethel Park', 'Mount Lebanon', 'Ross Township', 'Murrysville', 'Greensburg', 'Washington', 'Butler', 'Weirton', 'Wheeling'],
    description: 'The Pittsburgh metro area hosts Pokemon card shows and trading card events across western Pennsylvania and the northern panhandle of West Virginia.',
  },
  {
    slug: 'cincinnati',
    name: 'Cincinnati',
    state: 'OH',
    states: ['OH', 'KY', 'IN'],
    cities: ['Cincinnati', 'Covington', 'Florence', 'Hamilton', 'Fairfield', 'Mason', 'West Chester', 'Middletown', 'Norwood', 'Sharonville', 'Springdale', 'Newport', 'Lawrenceburg'],
    description: 'The Cincinnati metro area spans Ohio, Kentucky, and Indiana, hosting Pokemon card shows and trading card events throughout the tri-state region.',
  },
  {
    slug: 'raleigh',
    name: 'Raleigh/Durham',
    state: 'NC',
    states: ['NC'],
    cities: ['Raleigh', 'Durham', 'Chapel Hill', 'Cary', 'Apex', 'Wake Forest', 'Holly Springs', 'Fuquay-Varina', 'Garner', 'Morrisville', 'Knightdale', 'Clayton'],
    description: 'The Raleigh/Durham metro area is the Research Triangle\'s home for Pokemon card shows and trading card events in central North Carolina.',
  },
  {
    slug: 'milwaukee',
    name: 'Milwaukee',
    state: 'WI',
    states: ['WI'],
    cities: ['Milwaukee', 'Waukesha', 'West Allis', 'Wauwatosa', 'Brookfield', 'New Berlin', 'Menomonee Falls', 'Muskego', 'Greenfield', 'Franklin', 'Oak Creek', 'Racine', 'Kenosha'],
    description: 'The Milwaukee metro area hosts regular Pokemon card shows and trading card events across southeastern Wisconsin.',
  },
  {
    slug: 'oklahoma-city',
    name: 'Oklahoma City',
    state: 'OK',
    states: ['OK'],
    cities: ['Oklahoma City', 'Norman', 'Edmond', 'Moore', 'Midwest City', 'Yukon', 'Mustang', 'Del City', 'Bethany', 'El Reno', 'Shawnee', 'Stillwater'],
    description: 'The Oklahoma City metro area features Pokemon card shows and trading card events throughout central Oklahoma.',
  },
  {
    slug: 'tucson',
    name: 'Tucson',
    state: 'AZ',
    states: ['AZ'],
    cities: ['Tucson', 'Marana', 'Oro Valley', 'Sahuarita', 'South Tucson', 'Catalina Foothills', 'Casas Adobes', 'Green Valley', 'Sierra Vista', 'Vail'],
    description: 'The Tucson metro area hosts Pokemon card shows and trading card events in southern Arizona.',
  },
  {
    slug: 'jacksonville',
    name: 'Jacksonville',
    state: 'FL',
    states: ['FL', 'GA'],
    cities: ['Jacksonville', 'St. Augustine', 'Orange Park', 'Fleming Island', 'Ponte Vedra Beach', 'Fernandina Beach', 'Jacksonville Beach', 'Atlantic Beach', 'Brunswick', 'St. Marys'],
    description: 'The Jacksonville metro area hosts Pokemon card shows and trading card events across northeast Florida and southeast Georgia.',
  },
  {
    slug: 'memphis',
    name: 'Memphis',
    state: 'TN',
    states: ['TN', 'MS', 'AR'],
    cities: ['Memphis', 'Germantown', 'Collierville', 'Bartlett', 'Southaven', 'Olive Branch', 'Horn Lake', 'West Memphis', 'Marion', 'Millington'],
    description: 'The Memphis metro area spans Tennessee, Mississippi, and Arkansas, hosting Pokemon card shows and trading card events throughout the Mid-South.',
  },
  {
    slug: 'baltimore',
    name: 'Baltimore',
    state: 'MD',
    states: ['MD'],
    cities: ['Baltimore', 'Columbia', 'Towson', 'Ellicott City', 'Glen Burnie', 'Dundalk', 'Bel Air', 'Catonsville', 'Pikesville', 'Owings Mills', 'Annapolis', 'Laurel', 'Severna Park'],
    description: 'The Baltimore metro area hosts Pokemon card shows and trading card events throughout central Maryland.',
  },
  {
    slug: 'salt-lake-city',
    name: 'Salt Lake City',
    state: 'UT',
    states: ['UT'],
    cities: ['Salt Lake City', 'West Valley City', 'Provo', 'West Jordan', 'Orem', 'Sandy', 'Ogden', 'St. George', 'Layton', 'South Jordan', 'Lehi', 'Murray', 'Draper', 'Bountiful'],
    description: 'The Salt Lake City metro area is Utah\'s primary destination for Pokemon card shows and trading card events along the Wasatch Front.',
  },
  {
    slug: 'richmond',
    name: 'Richmond',
    state: 'VA',
    states: ['VA'],
    cities: ['Richmond', 'Henrico', 'Chesterfield', 'Midlothian', 'Glen Allen', 'Mechanicsville', 'Colonial Heights', 'Hopewell', 'Petersburg', 'Ashland', 'Chester'],
    description: 'The Richmond metro area hosts Pokemon card shows and trading card events throughout central Virginia.',
  },
  {
    slug: 'hartford',
    name: 'Hartford',
    state: 'CT',
    states: ['CT', 'MA'],
    cities: ['Hartford', 'New Haven', 'Stamford', 'Bridgeport', 'Waterbury', 'Norwalk', 'Danbury', 'New Britain', 'West Hartford', 'Meriden', 'Middletown', 'Bristol', 'Springfield', 'Chicopee'],
    description: 'The Hartford metro area hosts Pokemon card shows and trading card events across Connecticut and western Massachusetts.',
  },
  {
    slug: 'new-orleans',
    name: 'New Orleans',
    state: 'LA',
    states: ['LA', 'MS'],
    cities: ['New Orleans', 'Metairie', 'Kenner', 'Harvey', 'Marrero', 'Slidell', 'Chalmette', 'Mandeville', 'Covington', 'Hammond', 'Gulfport', 'Biloxi'],
    description: 'The New Orleans metro area hosts Pokemon card shows and trading card events across southeast Louisiana and the Mississippi Gulf Coast.',
  },
  {
    slug: 'louisville',
    name: 'Louisville',
    state: 'KY',
    states: ['KY', 'IN'],
    cities: ['Louisville', 'Jeffersonville', 'New Albany', 'Clarksville', 'Elizabethtown', 'Shepherdsville', 'Bardstown', 'Shelbyville', 'La Grange', 'Frankfort'],
    description: 'The Louisville metro area spans Kentucky and southern Indiana, hosting Pokemon card shows and trading card events throughout the region.',
  },
  {
    slug: 'buffalo',
    name: 'Buffalo',
    state: 'NY',
    states: ['NY'],
    cities: ['Buffalo', 'Cheektowaga', 'Tonawanda', 'Niagara Falls', 'Amherst', 'West Seneca', 'Hamburg', 'Orchard Park', 'Lackawanna', 'Depew', 'Williamsville', 'Lancaster'],
    description: 'The Buffalo metro area hosts Pokemon card shows and trading card events across western New York.',
  },
  {
    slug: 'rochester',
    name: 'Rochester',
    state: 'NY',
    states: ['NY'],
    cities: ['Rochester', 'Irondequoit', 'Greece', 'Brighton', 'Henrietta', 'Webster', 'Penfield', 'Pittsford', 'Gates', 'Victor', 'Fairport', 'Canandaigua', 'Batavia'],
    description: 'The Rochester metro area hosts Pokemon card shows and trading card events throughout the Finger Lakes region of New York.',
  },
  {
    slug: 'honolulu',
    name: 'Honolulu',
    state: 'HI',
    states: ['HI'],
    cities: ['Honolulu', 'Pearl City', 'Kailua', 'Kaneohe', 'Waipahu', 'Mililani', 'Ewa Beach', 'Kapolei', 'Aiea'],
    description: 'The Honolulu metro area hosts Pokemon card shows and trading card events across Oahu and the Hawaiian Islands.',
  },
  {
    slug: 'albuquerque',
    name: 'Albuquerque',
    state: 'NM',
    states: ['NM'],
    cities: ['Albuquerque', 'Rio Rancho', 'Santa Fe', 'Las Cruces', 'Los Lunas', 'Bernalillo', 'Corrales', 'Edgewood', 'Belen'],
    description: 'The Albuquerque metro area hosts Pokemon card shows and trading card events across central New Mexico.',
  },
  {
    slug: 'birmingham',
    name: 'Birmingham',
    state: 'AL',
    states: ['AL'],
    cities: ['Birmingham', 'Hoover', 'Vestavia Hills', 'Tuscaloosa', 'Bessemer', 'Homewood', 'Mountain Brook', 'Trussville', 'Pelham', 'Alabaster', 'Helena', 'Moody', 'Gardendale'],
    description: 'The Birmingham metro area hosts Pokemon card shows and trading card events throughout central Alabama.',
  },
];

export function getMetroBySlug(slug: string): Metro | undefined {
  return TOP_METROS.find((m) => m.slug === slug);
}

export function getAllMetroSlugs(): string[] {
  return TOP_METROS.map((m) => m.slug);
}
