import { BaseScraper, scrapedShowSchema, type ScrapedShow } from './base-scraper';

/**
 * "Scraper" that returns well-known, verified card shows from major organizers.
 * Acts as a reliable baseline when live scrapers can't reach JS-rendered sites.
 * All data sourced from official event websites.
 */

const SEED_EVENTS: ScrapedShow[] = [
  // ── Collect-A-Con ──────────────────────────────────────────────
  {
    name: 'Collect-A-Con Dallas 2025',
    description: 'The largest trading card & pop culture convention featuring 500+ vendor tables with sports cards, Pokemon, Yu-Gi-Oh!, Magic, Funko POPs, comics, and more.',
    venueName: 'Kay Bailey Hutchison Convention Center',
    address: '650 S Griffin St',
    city: 'Dallas',
    state: 'TX',
    zipCode: '75202',
    startDate: '2025-06-14',
    endDate: '2025-06-15',
    startTime: '10:00',
    endTime: '17:00',
    admissionPrice: '$55-$62/day',
    organizerName: 'Collect-A-Con',
    eventType: 'convention',
    isPokemonSpecific: false,
    sourceId: 'collectacon-dallas-2025',
    sourceName: 'seed_data',
    sourceUrl: 'https://collectaconusa.com/',
    websiteUrl: 'https://collectaconusa.com/',
  },
  {
    name: 'Collect-A-Con Atlanta 2025',
    description: 'Trading card & pop culture convention with 500+ vendor tables, celebrity guests, live breaks, and grading services.',
    venueName: 'Georgia World Congress Center Hall A1',
    address: '285 Andrew Young International Blvd NW',
    city: 'Atlanta',
    state: 'GA',
    zipCode: '30313',
    startDate: '2025-09-13',
    endDate: '2025-09-14',
    startTime: '10:00',
    endTime: '17:00',
    admissionPrice: '$55-$62/day',
    organizerName: 'Collect-A-Con',
    eventType: 'convention',
    isPokemonSpecific: false,
    sourceId: 'collectacon-atlanta-2025',
    sourceName: 'seed_data',
    sourceUrl: 'https://collectaconusa.com/',
    websiteUrl: 'https://collectaconusa.com/',
  },
  {
    name: 'Collect-A-Con Chicago 2025',
    description: 'Trading card & pop culture convention with 500+ vendor tables, celebrity guests, live breaks, and grading services.',
    venueName: 'Donald E. Stephens Convention Center',
    address: '5555 N River Rd',
    city: 'Rosemont',
    state: 'IL',
    zipCode: '60018',
    startDate: '2025-10-11',
    endDate: '2025-10-12',
    startTime: '10:00',
    endTime: '17:00',
    admissionPrice: '$55-$62/day',
    organizerName: 'Collect-A-Con',
    eventType: 'convention',
    isPokemonSpecific: false,
    sourceId: 'collectacon-chicago-2025',
    sourceName: 'seed_data',
    sourceUrl: 'https://collectaconusa.com/',
    websiteUrl: 'https://collectaconusa.com/',
  },
  {
    name: 'Collect-A-Con Los Angeles 2025',
    description: 'Trading card & pop culture convention with 500+ vendor tables, celebrity guests, live breaks, and grading services.',
    venueName: 'Los Angeles Convention Center',
    address: '1201 S Figueroa St',
    city: 'Los Angeles',
    state: 'CA',
    zipCode: '90015',
    startDate: '2025-12-20',
    endDate: '2025-12-21',
    startTime: '10:00',
    endTime: '17:00',
    admissionPrice: '$55-$62/day',
    organizerName: 'Collect-A-Con',
    eventType: 'convention',
    isPokemonSpecific: false,
    sourceId: 'collectacon-la-2025',
    sourceName: 'seed_data',
    sourceUrl: 'https://collectaconusa.com/',
    websiteUrl: 'https://collectaconusa.com/',
  },
  {
    name: 'Collect-A-Con Atlanta 2026',
    description: 'Trading card & pop culture convention with 500+ vendor tables, celebrity guests, live breaks, and grading services.',
    venueName: 'Georgia World Congress Center Hall A1',
    address: '285 Andrew Young International Blvd NW',
    city: 'Atlanta',
    state: 'GA',
    zipCode: '30313',
    startDate: '2026-02-07',
    endDate: '2026-02-08',
    startTime: '10:00',
    endTime: '17:00',
    admissionPrice: '$55-$62/day',
    organizerName: 'Collect-A-Con',
    eventType: 'convention',
    isPokemonSpecific: false,
    sourceId: 'collectacon-atlanta-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://collectaconusa.com/',
    websiteUrl: 'https://collectaconusa.com/',
  },
  {
    name: 'Collect-A-Con Fort Lauderdale 2026',
    description: 'Trading card & pop culture convention with 500+ vendor tables, celebrity guests, live breaks, and grading services.',
    venueName: 'Broward County Convention Center Hall A',
    address: '1950 Eisenhower Blvd',
    city: 'Fort Lauderdale',
    state: 'FL',
    zipCode: '33316',
    startDate: '2026-02-21',
    endDate: '2026-02-22',
    startTime: '10:00',
    endTime: '17:00',
    admissionPrice: '$55-$62/day',
    organizerName: 'Collect-A-Con',
    eventType: 'convention',
    isPokemonSpecific: false,
    sourceId: 'collectacon-ftl-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://collectaconusa.com/',
    websiteUrl: 'https://collectaconusa.com/',
  },
  {
    name: 'Collect-A-Con Fort Worth 2026',
    description: 'Trading card & pop culture convention with 500+ vendor tables, celebrity guests, live breaks, and grading services.',
    venueName: 'Fort Worth Convention Center',
    address: '1201 Houston St',
    city: 'Fort Worth',
    state: 'TX',
    zipCode: '76102',
    startDate: '2026-04-04',
    endDate: '2026-04-05',
    startTime: '10:00',
    endTime: '17:00',
    admissionPrice: '$55-$62/day',
    organizerName: 'Collect-A-Con',
    eventType: 'convention',
    isPokemonSpecific: false,
    sourceId: 'collectacon-ftw-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://collectaconusa.com/',
    websiteUrl: 'https://collectaconusa.com/',
  },
  {
    name: 'Collect-A-Con Cleveland 2026',
    description: 'Trading card & pop culture convention with 500+ vendor tables, celebrity guests, live breaks, and grading services.',
    venueName: 'Huntington Convention Center of Cleveland',
    address: '300 Lakeside Ave E',
    city: 'Cleveland',
    state: 'OH',
    zipCode: '44114',
    startDate: '2026-05-09',
    endDate: '2026-05-10',
    startTime: '10:00',
    endTime: '17:00',
    admissionPrice: '$55-$62/day',
    organizerName: 'Collect-A-Con',
    eventType: 'convention',
    isPokemonSpecific: false,
    sourceId: 'collectacon-cleveland-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://collectaconusa.com/',
    websiteUrl: 'https://collectaconusa.com/',
  },
  {
    name: 'Collect-A-Con Kansas City 2026',
    description: 'Trading card & pop culture convention with 500+ vendor tables, celebrity guests, live breaks, and grading services.',
    venueName: 'Kansas City Convention Center',
    address: '301 W 13th St',
    city: 'Kansas City',
    state: 'MO',
    zipCode: '64105',
    startDate: '2026-06-13',
    endDate: '2026-06-14',
    startTime: '10:00',
    endTime: '17:00',
    admissionPrice: '$55-$62/day',
    organizerName: 'Collect-A-Con',
    eventType: 'convention',
    isPokemonSpecific: false,
    sourceId: 'collectacon-kc-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://collectaconusa.com/',
    websiteUrl: 'https://collectaconusa.com/',
  },
  {
    name: 'Collect-A-Con Edison 2026',
    description: 'Trading card & pop culture convention with 500+ vendor tables, celebrity guests, live breaks, and grading services.',
    venueName: 'New Jersey Convention & Exposition Center',
    address: '97 Sunfield Ave',
    city: 'Edison',
    state: 'NJ',
    zipCode: '08837',
    startDate: '2026-07-11',
    endDate: '2026-07-12',
    startTime: '10:00',
    endTime: '17:00',
    admissionPrice: '$55-$62/day',
    organizerName: 'Collect-A-Con',
    eventType: 'convention',
    isPokemonSpecific: false,
    sourceId: 'collectacon-edison-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://collectaconusa.com/',
    websiteUrl: 'https://collectaconusa.com/',
  },
  {
    name: 'Collect-A-Con Atlanta Fall 2026',
    description: 'Trading card & pop culture convention with 500+ vendor tables, celebrity guests, live breaks, and grading services.',
    venueName: 'Georgia World Congress Center',
    address: '285 Andrew Young International Blvd NW',
    city: 'Atlanta',
    state: 'GA',
    zipCode: '30313',
    startDate: '2026-09-26',
    endDate: '2026-09-27',
    startTime: '10:00',
    endTime: '17:00',
    admissionPrice: '$55-$62/day',
    organizerName: 'Collect-A-Con',
    eventType: 'convention',
    isPokemonSpecific: false,
    sourceId: 'collectacon-atlanta-fall-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://collectaconusa.com/',
    websiteUrl: 'https://collectaconusa.com/',
  },

  // ── The National (NSCC) ────────────────────────────────────────
  {
    name: '45th National Sports Collectors Convention',
    description: 'The largest and most prestigious annual sports card and memorabilia show in the country, running for 45+ years. Features thousands of dealer tables, autograph guests, and special events.',
    venueName: 'Donald E. Stephens Convention Center',
    address: '5555 N River Rd',
    city: 'Rosemont',
    state: 'IL',
    zipCode: '60018',
    startDate: '2025-07-30',
    endDate: '2025-08-03',
    startTime: '10:00',
    endTime: '17:00',
    admissionPrice: '$30/day',
    organizerName: 'NSCC',
    eventType: 'convention',
    isPokemonSpecific: false,
    sourceId: 'nscc-2025',
    sourceName: 'seed_data',
    sourceUrl: 'https://www.nsccshow.com',
    websiteUrl: 'https://www.nsccshow.com',
  },
  {
    name: '46th National Sports Collectors Convention',
    description: 'The largest and most prestigious annual sports card and memorabilia show in the country. Features thousands of dealer tables, autograph guests, and special events.',
    venueName: 'Donald E. Stephens Convention Center',
    address: '5555 N River Rd',
    city: 'Rosemont',
    state: 'IL',
    zipCode: '60018',
    startDate: '2026-07-29',
    endDate: '2026-08-02',
    startTime: '10:00',
    endTime: '17:00',
    admissionPrice: '$25 advance / $30 door',
    organizerName: 'NSCC',
    eventType: 'convention',
    isPokemonSpecific: false,
    sourceId: 'nscc-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://www.nsccshow.com',
    websiteUrl: 'https://www.nsccshow.com',
  },

  // ── Best Flippin' Card Show ────────────────────────────────────
  {
    name: "Best Flippin' Card Show at Polar Park",
    description: 'TCG-focused card show featuring Pokemon, sports cards, and other TCGs at Polar Park stadium.',
    venueName: 'Polar Park',
    address: '100 Madison St',
    city: 'Worcester',
    state: 'MA',
    zipCode: '01608',
    startDate: '2025-07-26',
    startTime: '10:00',
    endTime: '16:00',
    organizerName: 'Best Flippin Card Show',
    eventType: 'card_show',
    isPokemonSpecific: false,
    sourceId: 'flippin-polar-park-2025',
    sourceName: 'seed_data',
    sourceUrl: 'https://flippincardshow.com/',
    websiteUrl: 'https://flippincardshow.com/',
  },
  {
    name: "Best Flippin' TCG Show Philadelphia",
    description: 'Major TCG show in the Greater Philadelphia area with hundreds of vendors selling Pokemon, sports, and other trading cards.',
    venueName: 'Greater Philly Expo Center',
    address: '100 Station Ave',
    city: 'Oaks',
    state: 'PA',
    zipCode: '19456',
    startDate: '2025-09-07',
    startTime: '10:00',
    endTime: '16:00',
    organizerName: 'Best Flippin Card Show',
    eventType: 'card_show',
    isPokemonSpecific: false,
    sourceId: 'flippin-philly-2025',
    sourceName: 'seed_data',
    sourceUrl: 'https://flippincardshow.com/',
    websiteUrl: 'https://flippincardshow.com/',
  },
  {
    name: "Best Flippin' TCG Show Baltimore 2026",
    description: 'Major TCG show in Baltimore with hundreds of vendors selling Pokemon, sports, and other trading cards.',
    venueName: 'Baltimore Convention Center',
    address: '1 W Pratt St',
    city: 'Baltimore',
    state: 'MD',
    zipCode: '21201',
    startDate: '2026-04-11',
    endDate: '2026-04-12',
    startTime: '10:00',
    endTime: '16:00',
    organizerName: 'Best Flippin Card Show',
    eventType: 'card_show',
    isPokemonSpecific: false,
    sourceId: 'flippin-baltimore-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://flippincardshow.com/',
    websiteUrl: 'https://flippincardshow.com/',
  },

  // ── Dallas Card Show ───────────────────────────────────────────
  {
    name: 'Dallas Card Show September 2025',
    description: 'The largest recurring regional sports card show in the US with 700+ vendor tables, auction houses, card grading, and Trade Night.',
    venueName: 'Marriott Dallas Allen Hotel & Convention Center',
    address: '800 Central Expy S',
    city: 'Allen',
    state: 'TX',
    zipCode: '75013',
    startDate: '2025-09-04',
    endDate: '2025-09-07',
    startTime: '10:00',
    endTime: '17:00',
    organizerName: 'Dallas Card Show',
    eventType: 'card_show',
    isPokemonSpecific: false,
    sourceId: 'dallas-card-show-sep-2025',
    sourceName: 'seed_data',
    sourceUrl: 'https://www.dallascardshow.com/',
    websiteUrl: 'https://www.dallascardshow.com/',
  },
  {
    name: 'Dallas Card Show March 2026',
    description: 'The largest recurring regional sports card show in the US with 700+ vendor tables, auction houses, card grading, and Trade Night.',
    venueName: 'Delta Hotels by Marriott Dallas Allen',
    address: '800 Central Expy S',
    city: 'Allen',
    state: 'TX',
    zipCode: '75013',
    startDate: '2026-03-12',
    endDate: '2026-03-15',
    startTime: '10:00',
    endTime: '17:00',
    organizerName: 'Dallas Card Show',
    eventType: 'card_show',
    isPokemonSpecific: false,
    sourceId: 'dallas-card-show-mar-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://www.dallascardshow.com/',
    websiteUrl: 'https://www.dallascardshow.com/',
  },

  // ── West Coast Card Show ───────────────────────────────────────
  {
    name: 'West Coast Card Show Anaheim 2025',
    description: 'The largest sports card event in the western United States with hundreds of vendor tables.',
    venueName: 'Anaheim Convention Center',
    address: '800 W Katella Ave',
    city: 'Anaheim',
    state: 'CA',
    zipCode: '92802',
    startDate: '2025-08-21',
    endDate: '2025-08-24',
    startTime: '10:00',
    endTime: '17:00',
    admissionPrice: '$30-$35/day',
    organizerName: 'West Coast Card Show',
    eventType: 'convention',
    isPokemonSpecific: false,
    sourceId: 'wccs-anaheim-2025',
    sourceName: 'seed_data',
    sourceUrl: 'https://westcoastcardshow.com/',
    websiteUrl: 'https://westcoastcardshow.com/',
  },
  {
    name: 'West Coast Card Show Sports Edition 2026',
    description: 'The largest sports card event in the western United States with hundreds of vendor tables.',
    venueName: 'Ontario Convention Center',
    address: '2000 E Convention Center Way',
    city: 'Ontario',
    state: 'CA',
    zipCode: '91764',
    startDate: '2026-02-12',
    endDate: '2026-02-15',
    startTime: '10:00',
    endTime: '17:00',
    admissionPrice: '$30-$35/day',
    organizerName: 'West Coast Card Show',
    eventType: 'convention',
    isPokemonSpecific: false,
    sourceId: 'wccs-ontario-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://westcoastcardshow.com/',
    websiteUrl: 'https://westcoastcardshow.com/',
  },
  {
    name: 'West Coast Card Show Summer 2026',
    description: 'The largest sports card event in the western United States with hundreds of vendor tables.',
    venueName: 'Anaheim Convention Center',
    address: '800 W Katella Ave',
    city: 'Anaheim',
    state: 'CA',
    zipCode: '92802',
    startDate: '2026-07-16',
    endDate: '2026-07-19',
    startTime: '10:00',
    endTime: '17:00',
    admissionPrice: '$30-$35/day',
    organizerName: 'West Coast Card Show',
    eventType: 'convention',
    isPokemonSpecific: false,
    sourceId: 'wccs-anaheim-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://westcoastcardshow.com/',
    websiteUrl: 'https://westcoastcardshow.com/',
  },

  // ── Front Row Card Show ────────────────────────────────────────
  {
    name: 'Front Row Card Show Seattle/Tacoma',
    description: 'Multi-city card show featuring sports cards, TCGs, comic books, and collectibles with 600+ tables.',
    venueName: 'Greater Tacoma Convention Center',
    address: '1500 Commerce St',
    city: 'Tacoma',
    state: 'WA',
    zipCode: '98402',
    startDate: '2025-10-25',
    endDate: '2025-10-26',
    startTime: '10:00',
    endTime: '17:00',
    organizerName: 'Front Row Card Show',
    eventType: 'card_show',
    isPokemonSpecific: false,
    sourceId: 'frontrow-tacoma-2025',
    sourceName: 'seed_data',
    sourceUrl: 'https://frontrowcardshow.com/',
    websiteUrl: 'https://frontrowcardshow.com/',
  },
  {
    name: 'Front Row Card Show Las Vegas',
    description: 'Multi-city card show featuring sports cards, TCGs, comic books, and collectibles with 600+ tables.',
    venueName: 'Rio All-Suites Hotel & Casino',
    address: '3700 W Flamingo Rd',
    city: 'Las Vegas',
    state: 'NV',
    zipCode: '89103',
    startDate: '2025-11-08',
    endDate: '2025-11-09',
    startTime: '10:00',
    endTime: '17:00',
    organizerName: 'Front Row Card Show',
    eventType: 'card_show',
    isPokemonSpecific: false,
    sourceId: 'frontrow-vegas-2025',
    sourceName: 'seed_data',
    sourceUrl: 'https://frontrowcardshow.com/',
    websiteUrl: 'https://frontrowcardshow.com/',
  },
  {
    name: 'Front Row Card Show Pasadena',
    description: 'Multi-city card show featuring sports cards, TCGs, comic books, and collectibles with 600+ tables.',
    venueName: 'Pasadena Convention Center',
    address: '300 E Green St',
    city: 'Pasadena',
    state: 'CA',
    zipCode: '91101',
    startDate: '2025-11-22',
    endDate: '2025-11-23',
    startTime: '10:00',
    endTime: '17:00',
    organizerName: 'Front Row Card Show',
    eventType: 'card_show',
    isPokemonSpecific: false,
    sourceId: 'frontrow-pasadena-2025',
    sourceName: 'seed_data',
    sourceUrl: 'https://frontrowcardshow.com/',
    websiteUrl: 'https://frontrowcardshow.com/',
  },
  {
    name: 'Front Row Card Show San Diego 2026',
    description: 'Multi-city card show featuring sports cards, TCGs, comic books, and collectibles with 600+ tables.',
    venueName: 'San Diego Convention Center',
    address: '111 W Harbor Dr',
    city: 'San Diego',
    state: 'CA',
    zipCode: '92101',
    startDate: '2026-01-17',
    endDate: '2026-01-18',
    startTime: '10:00',
    endTime: '17:00',
    organizerName: 'Front Row Card Show',
    eventType: 'card_show',
    isPokemonSpecific: false,
    sourceId: 'frontrow-sd-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://frontrowcardshow.com/',
    websiteUrl: 'https://frontrowcardshow.com/',
  },

  // ── Northeast Sports Card Expo ─────────────────────────────────
  {
    name: 'Northeast Sports Card Expo Connecticut',
    description: 'Growing card show circuit in New England featuring sports cards, Pokemon, and other collectible cards.',
    venueName: 'Chelsea Piers Connecticut',
    address: '1 Blachley Rd',
    city: 'Stamford',
    state: 'CT',
    zipCode: '06902',
    startDate: '2025-09-13',
    endDate: '2025-09-14',
    startTime: '10:00',
    endTime: '17:00',
    admissionPrice: '$15-$20/day',
    organizerName: 'Northeast Sports Card Expo',
    eventType: 'card_show',
    isPokemonSpecific: false,
    sourceId: 'nsce-ct-2025',
    sourceName: 'seed_data',
    sourceUrl: 'https://www.northeastcardexpo.com/',
    websiteUrl: 'https://www.northeastcardexpo.com/',
  },
  {
    name: 'Northeast Sports Card Expo Portland',
    description: 'Growing card show circuit in New England featuring sports cards, Pokemon, and other collectible cards.',
    venueName: 'Portland Expo Building',
    address: '239 Park Ave',
    city: 'Portland',
    state: 'ME',
    zipCode: '04102',
    startDate: '2025-10-18',
    endDate: '2025-10-19',
    startTime: '10:00',
    endTime: '17:00',
    admissionPrice: '$15-$20/day',
    organizerName: 'Northeast Sports Card Expo',
    eventType: 'card_show',
    isPokemonSpecific: false,
    sourceId: 'nsce-portland-2025',
    sourceName: 'seed_data',
    sourceUrl: 'https://www.northeastcardexpo.com/',
    websiteUrl: 'https://www.northeastcardexpo.com/',
  },
  {
    name: 'Northeast Sports Card Expo Quincy',
    description: 'Growing card show circuit in New England featuring sports cards, Pokemon, and other collectible cards.',
    venueName: 'Marriott Boston Quincy',
    address: '1000 Marriott Dr',
    city: 'Quincy',
    state: 'MA',
    zipCode: '02169',
    startDate: '2025-11-22',
    endDate: '2025-11-23',
    startTime: '10:00',
    endTime: '17:00',
    admissionPrice: '$15-$20/day',
    organizerName: 'Northeast Sports Card Expo',
    eventType: 'card_show',
    isPokemonSpecific: false,
    sourceId: 'nsce-quincy-2025',
    sourceName: 'seed_data',
    sourceUrl: 'https://www.northeastcardexpo.com/',
    websiteUrl: 'https://www.northeastcardexpo.com/',
  },
  {
    name: 'Northeast Sports Card Expo Connecticut 2026',
    description: 'Growing card show circuit in New England featuring sports cards, Pokemon, and other collectible cards.',
    venueName: 'Chelsea Piers Connecticut',
    address: '1 Blachley Rd',
    city: 'Stamford',
    state: 'CT',
    zipCode: '06902',
    startDate: '2026-05-02',
    endDate: '2026-05-03',
    startTime: '10:00',
    endTime: '17:00',
    admissionPrice: '$15-$20/day',
    organizerName: 'Northeast Sports Card Expo',
    eventType: 'card_show',
    isPokemonSpecific: false,
    sourceId: 'nsce-ct-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://www.northeastcardexpo.com/',
    websiteUrl: 'https://www.northeastcardexpo.com/',
  },

  // ── Pokemon-Specific Events ────────────────────────────────────
  {
    name: 'PokemonXP 2026',
    description: 'The first-ever official Pokemon fan convention hosted by The Pokemon Company. Features exclusive experiences, tournaments, merchandise, and the Pokemon World Championship.',
    venueName: 'Moscone Center',
    address: '747 Howard St',
    city: 'San Francisco',
    state: 'CA',
    zipCode: '94103',
    startDate: '2026-08-28',
    endDate: '2026-08-30',
    startTime: '10:00',
    endTime: '18:00',
    admissionPrice: '$120 single-day / $150 multi-day',
    organizerName: 'The Pokemon Company International',
    eventType: 'convention',
    isPokemonSpecific: true,
    sourceId: 'pokemonxp-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://registration.pokemon.com/flow/pokemon/26sanfrancisco/landing/page/main',
    websiteUrl: 'https://registration.pokemon.com/flow/pokemon/26sanfrancisco/landing/page/main',
  },
  {
    name: 'Card Party 4 San Diego',
    description: 'Pokemon creator & collector card show featuring vendors, live breaks, tournaments, meet-and-greets with top Pokemon content creators.',
    venueName: 'Gaylord Pacific Resort & Convention Center',
    address: '1000 H St',
    city: 'Chula Vista',
    state: 'CA',
    zipCode: '91910',
    startDate: '2026-05-22',
    endDate: '2026-05-24',
    startTime: '10:00',
    endTime: '17:00',
    organizerName: 'Card Party',
    eventType: 'convention',
    isPokemonSpecific: true,
    sourceId: 'card-party-sd-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://www.card.party/',
    websiteUrl: 'https://www.card.party/',
  },
  {
    name: 'Card Party South Florida',
    description: 'Pokemon card convention featuring vendors, live breaks, tournaments, and meet-and-greets with top Pokemon content creators.',
    venueName: 'Fort Lauderdale Convention Center',
    address: '1950 Eisenhower Blvd',
    city: 'Fort Lauderdale',
    state: 'FL',
    zipCode: '33316',
    startDate: '2026-07-24',
    endDate: '2026-07-26',
    startTime: '10:00',
    endTime: '17:00',
    organizerName: 'Card Party',
    eventType: 'convention',
    isPokemonSpecific: true,
    sourceId: 'card-party-fl-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://www.card.party/',
    websiteUrl: 'https://www.card.party/',
  },
  {
    name: 'Card Party Dallas',
    description: 'Pokemon card convention featuring vendors, live breaks, tournaments, and meet-and-greets with top Pokemon content creators.',
    venueName: 'Gaylord Texan Resort & Convention Center',
    address: '1501 Gaylord Trail',
    city: 'Grapevine',
    state: 'TX',
    zipCode: '76051',
    startDate: '2026-09-04',
    endDate: '2026-09-06',
    startTime: '10:00',
    endTime: '17:00',
    organizerName: 'Card Party',
    eventType: 'convention',
    isPokemonSpecific: true,
    sourceId: 'card-party-dallas-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://www.card.party/',
    websiteUrl: 'https://www.card.party/',
  },

  // ── PokeKon Fest (Pokemon-specific touring show) ───────────────
  {
    name: 'PokeKon Fest Cleveland',
    description: 'All-Pokemon trading card show touring 30+ cities. Buy, sell, and trade Pokemon cards with local collectors and vendors.',
    venueName: 'Wyndham Garden Hotel',
    address: '1100 Crocker Rd',
    city: 'Westlake',
    state: 'OH',
    zipCode: '44145',
    startDate: '2026-02-14',
    startTime: '10:00',
    endTime: '16:00',
    admissionPrice: '$20',
    organizerName: 'PokeKon',
    eventType: 'card_show',
    isPokemonSpecific: true,
    sourceId: 'pokekon-cleveland-2026',
    sourceName: 'seed_data',
    sourceUrl: 'http://pokekon.com/',
    websiteUrl: 'http://pokekon.com/',
  },
  {
    name: 'PokeKon Fest St. Louis',
    description: 'All-Pokemon trading card show touring 30+ cities. Buy, sell, and trade Pokemon cards with local collectors and vendors.',
    venueName: 'Radisson Hotel Downtown St. Louis',
    address: '200 N 4th St',
    city: 'St. Louis',
    state: 'MO',
    zipCode: '63102',
    startDate: '2026-02-07',
    startTime: '10:00',
    endTime: '16:00',
    admissionPrice: '$20',
    organizerName: 'PokeKon',
    eventType: 'card_show',
    isPokemonSpecific: true,
    sourceId: 'pokekon-stl-2026',
    sourceName: 'seed_data',
    sourceUrl: 'http://pokekon.com/',
    websiteUrl: 'http://pokekon.com/',
  },
  {
    name: 'PokeKon Fest Richmond',
    description: 'All-Pokemon trading card show touring 30+ cities. Buy, sell, and trade Pokemon cards with local collectors and vendors.',
    venueName: 'Richmond Convention Center',
    address: '403 N 3rd St',
    city: 'Richmond',
    state: 'VA',
    zipCode: '23219',
    startDate: '2026-02-07',
    startTime: '10:00',
    endTime: '16:00',
    admissionPrice: '$20',
    organizerName: 'PokeKon',
    eventType: 'card_show',
    isPokemonSpecific: true,
    sourceId: 'pokekon-richmond-2026',
    sourceName: 'seed_data',
    sourceUrl: 'http://pokekon.com/',
    websiteUrl: 'http://pokekon.com/',
  },
  {
    name: 'PokeKon Fest Rochester',
    description: 'All-Pokemon trading card show touring 30+ cities. Buy, sell, and trade Pokemon cards with local collectors and vendors.',
    venueName: 'Rochester Riverside Convention Center',
    address: '123 E Main St',
    city: 'Rochester',
    state: 'NY',
    zipCode: '14604',
    startDate: '2026-01-10',
    startTime: '10:00',
    endTime: '16:00',
    admissionPrice: '$20',
    organizerName: 'PokeKon',
    eventType: 'card_show',
    isPokemonSpecific: true,
    sourceId: 'pokekon-rochester-2026',
    sourceName: 'seed_data',
    sourceUrl: 'http://pokekon.com/',
    websiteUrl: 'http://pokekon.com/',
  },
  {
    name: 'PokeKon Fest Kentucky',
    description: 'All-Pokemon trading card show touring 30+ cities. Buy, sell, and trade Pokemon cards with local collectors and vendors.',
    venueName: 'Holiday Inn Cincinnati Airport',
    address: '1717 Airport Exchange Blvd',
    city: 'Hebron',
    state: 'KY',
    zipCode: '41048',
    startDate: '2026-01-25',
    startTime: '10:00',
    endTime: '16:00',
    admissionPrice: '$20',
    organizerName: 'PokeKon',
    eventType: 'card_show',
    isPokemonSpecific: true,
    sourceId: 'pokekon-ky-2026',
    sourceName: 'seed_data',
    sourceUrl: 'http://pokekon.com/',
    websiteUrl: 'http://pokekon.com/',
  },

  // ── Pokemon NAIC ───────────────────────────────────────────────
  {
    name: '2025 Pokemon North America International Championships',
    description: 'Official Pokemon competitive event featuring the Pokemon TCG, video game, and Pokemon Unite tournaments. Open to qualified players and spectators.',
    venueName: 'Ernest N. Morial Convention Center',
    address: '900 Convention Center Blvd',
    city: 'New Orleans',
    state: 'LA',
    zipCode: '70130',
    startDate: '2025-06-13',
    endDate: '2025-06-15',
    startTime: '09:00',
    endTime: '18:00',
    organizerName: 'The Pokemon Company International',
    eventType: 'tournament',
    isPokemonSpecific: true,
    sourceId: 'naic-2025',
    sourceName: 'seed_data',
    sourceUrl: 'https://www.pokemon.com/us/play-pokemon/internationals/2025/north-america/about',
    websiteUrl: 'https://www.pokemon.com/us/play-pokemon/internationals/2025/north-america/about',
  },
  {
    name: '2026 Pokemon North America International Championships',
    description: 'Official Pokemon competitive event featuring the Pokemon TCG, video game, and Pokemon Unite tournaments. Open to qualified players and spectators.',
    venueName: 'Ernest N. Morial Convention Center',
    address: '900 Convention Center Blvd',
    city: 'New Orleans',
    state: 'LA',
    zipCode: '70130',
    startDate: '2026-06-12',
    endDate: '2026-06-14',
    startTime: '09:00',
    endTime: '18:00',
    organizerName: 'The Pokemon Company International',
    eventType: 'tournament',
    isPokemonSpecific: true,
    sourceId: 'naic-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://www.pokemon.com/us/play-pokemon/',
    websiteUrl: 'https://www.pokemon.com/us/play-pokemon/',
  },

  // ── Miami TCG Convention ───────────────────────────────────────
  {
    name: 'Miami TCG Convention January 2026',
    description: 'TCG-focused convention in Miami featuring Pokemon, Yu-Gi-Oh!, One Piece, and other trading card games. Vendors, tournaments, and grading services.',
    venueName: 'Miami Airport Convention Center',
    address: '711 NW 72nd Ave',
    city: 'Miami',
    state: 'FL',
    zipCode: '33126',
    startDate: '2026-01-17',
    endDate: '2026-01-18',
    startTime: '10:00',
    endTime: '17:00',
    organizerName: 'Miami TCG Convention',
    eventType: 'convention',
    isPokemonSpecific: false,
    sourceId: 'miami-tcg-jan-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://miamitcgconvention.com/',
    websiteUrl: 'https://miamitcgconvention.com/',
  },
  {
    name: 'Miami TCG Convention March 2026',
    description: 'TCG-focused convention featuring Pokemon, Yu-Gi-Oh!, One Piece, and other trading card games. Vendors, tournaments, and grading services.',
    venueName: 'G-Star Studios',
    address: '2060 S Congress Ave',
    city: 'Palm Springs',
    state: 'FL',
    zipCode: '33406',
    startDate: '2026-03-07',
    endDate: '2026-03-08',
    startTime: '10:00',
    endTime: '17:00',
    organizerName: 'Miami TCG Convention',
    eventType: 'convention',
    isPokemonSpecific: false,
    sourceId: 'miami-tcg-mar-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://miamitcgconvention.com/',
    websiteUrl: 'https://miamitcgconvention.com/',
  },

  // ── Collectors Expo ────────────────────────────────────────────
  {
    name: 'Collectors Expo Dallas 2025',
    description: 'Features Pokemon, Yu-Gi-Oh!, One Piece, vintage collectibles, Funko Pops, retro video games, and more.',
    venueName: 'Kay Bailey Hutchison Convention Center',
    address: '650 S Griffin St',
    city: 'Dallas',
    state: 'TX',
    zipCode: '75202',
    startDate: '2025-11-15',
    endDate: '2025-11-16',
    startTime: '10:00',
    endTime: '17:00',
    organizerName: 'Collectors Expo',
    eventType: 'convention',
    isPokemonSpecific: false,
    sourceId: 'collectors-expo-dallas-2025',
    sourceName: 'seed_data',
    sourceUrl: 'https://www.collectorsexpo.com/',
    websiteUrl: 'https://www.collectorsexpo.com/',
  },

  // ── TCG MegaCon ────────────────────────────────────────────────
  {
    name: 'TCG MegaCon Austin 2026',
    description: 'Multi-city TCG convention tour featuring Pokemon, Yu-Gi-Oh!, Magic the Gathering, and more trading card games.',
    venueName: 'Pflugerville Event Center',
    address: '203 E Pecan St',
    city: 'Pflugerville',
    state: 'TX',
    zipCode: '78660',
    startDate: '2026-01-30',
    endDate: '2026-02-01',
    startTime: '10:00',
    endTime: '17:00',
    organizerName: 'TCG MegaCon',
    eventType: 'convention',
    isPokemonSpecific: false,
    sourceId: 'tcg-megacon-austin-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://tcgmegacon.com/',
    websiteUrl: 'https://tcgmegacon.com/',
  },
  {
    name: 'TCG MegaCon Tampa 2026',
    description: 'Multi-city TCG convention tour featuring Pokemon, Yu-Gi-Oh!, Magic the Gathering, and more trading card games.',
    venueName: 'Tampa Convention Center',
    address: '333 S Franklin St',
    city: 'Tampa',
    state: 'FL',
    zipCode: '33602',
    startDate: '2026-02-06',
    endDate: '2026-02-08',
    startTime: '10:00',
    endTime: '17:00',
    organizerName: 'TCG MegaCon',
    eventType: 'convention',
    isPokemonSpecific: false,
    sourceId: 'tcg-megacon-tampa-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://tcgmegacon.com/',
    websiteUrl: 'https://tcgmegacon.com/',
  },
  {
    name: 'TCG MegaCon Tucson 2026',
    description: 'Multi-city TCG convention tour featuring Pokemon, Yu-Gi-Oh!, Magic the Gathering, and more trading card games.',
    venueName: 'Tucson Convention Center',
    address: '260 S Church Ave',
    city: 'Tucson',
    state: 'AZ',
    zipCode: '85701',
    startDate: '2026-02-20',
    endDate: '2026-02-22',
    startTime: '10:00',
    endTime: '17:00',
    organizerName: 'TCG MegaCon',
    eventType: 'convention',
    isPokemonSpecific: false,
    sourceId: 'tcg-megacon-tucson-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://tcgmegacon.com/',
    websiteUrl: 'https://tcgmegacon.com/',
  },

  // ── March 2026 Shows ─────────────────────────────────────────
  {
    name: 'PokeKon Fest Nashville',
    description: 'All-Pokemon trading card show touring 30+ cities. Buy, sell, and trade Pokemon cards with local collectors and vendors.',
    venueName: 'Nashville Music City Center',
    address: '201 Rep. John Lewis Way S',
    city: 'Nashville',
    state: 'TN',
    zipCode: '37203',
    startDate: '2026-03-07',
    startTime: '10:00',
    endTime: '16:00',
    admissionPrice: '$20',
    organizerName: 'PokeKon',
    eventType: 'card_show',
    isPokemonSpecific: true,
    sourceId: 'pokekon-nashville-2026',
    sourceName: 'seed_data',
    sourceUrl: 'http://pokekon.com/',
    websiteUrl: 'http://pokekon.com/',
  },
  {
    name: 'PokeKon Fest Denver',
    description: 'All-Pokemon trading card show touring 30+ cities. Buy, sell, and trade Pokemon cards with local collectors and vendors.',
    venueName: 'DoubleTree by Hilton Denver',
    address: '3203 Quebec St',
    city: 'Denver',
    state: 'CO',
    zipCode: '80207',
    startDate: '2026-03-14',
    startTime: '10:00',
    endTime: '16:00',
    admissionPrice: '$20',
    organizerName: 'PokeKon',
    eventType: 'card_show',
    isPokemonSpecific: true,
    sourceId: 'pokekon-denver-2026',
    sourceName: 'seed_data',
    sourceUrl: 'http://pokekon.com/',
    websiteUrl: 'http://pokekon.com/',
  },
  {
    name: 'PokeKon Fest Atlanta',
    description: 'All-Pokemon trading card show touring 30+ cities. Buy, sell, and trade Pokemon cards with local collectors and vendors.',
    venueName: 'Atlanta Marriott Marquis',
    address: '265 Peachtree Center Ave NE',
    city: 'Atlanta',
    state: 'GA',
    zipCode: '30303',
    startDate: '2026-03-21',
    startTime: '10:00',
    endTime: '16:00',
    admissionPrice: '$20',
    organizerName: 'PokeKon',
    eventType: 'card_show',
    isPokemonSpecific: true,
    sourceId: 'pokekon-atlanta-2026',
    sourceName: 'seed_data',
    sourceUrl: 'http://pokekon.com/',
    websiteUrl: 'http://pokekon.com/',
  },
  {
    name: 'PokeKon Fest Charlotte',
    description: 'All-Pokemon trading card show touring 30+ cities. Buy, sell, and trade Pokemon cards with local collectors and vendors.',
    venueName: 'Hilton Charlotte University Place',
    address: '8629 JM Keynes Dr',
    city: 'Charlotte',
    state: 'NC',
    zipCode: '28262',
    startDate: '2026-03-28',
    startTime: '10:00',
    endTime: '16:00',
    admissionPrice: '$20',
    organizerName: 'PokeKon',
    eventType: 'card_show',
    isPokemonSpecific: true,
    sourceId: 'pokekon-charlotte-2026',
    sourceName: 'seed_data',
    sourceUrl: 'http://pokekon.com/',
    websiteUrl: 'http://pokekon.com/',
  },
  {
    name: 'TCG MegaCon Denver 2026',
    description: 'Multi-city TCG convention tour featuring Pokemon, Yu-Gi-Oh!, Magic the Gathering, and more trading card games.',
    venueName: 'National Western Complex',
    address: '4655 Humboldt St',
    city: 'Denver',
    state: 'CO',
    zipCode: '80216',
    startDate: '2026-03-06',
    endDate: '2026-03-08',
    startTime: '10:00',
    endTime: '17:00',
    organizerName: 'TCG MegaCon',
    eventType: 'convention',
    isPokemonSpecific: false,
    sourceId: 'tcg-megacon-denver-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://tcgmegacon.com/',
    websiteUrl: 'https://tcgmegacon.com/',
  },
  {
    name: 'TCG MegaCon Houston 2026',
    description: 'Multi-city TCG convention tour featuring Pokemon, Yu-Gi-Oh!, Magic the Gathering, and more trading card games.',
    venueName: 'NRG Center',
    address: '1 NRG Park',
    city: 'Houston',
    state: 'TX',
    zipCode: '77054',
    startDate: '2026-03-20',
    endDate: '2026-03-22',
    startTime: '10:00',
    endTime: '17:00',
    organizerName: 'TCG MegaCon',
    eventType: 'convention',
    isPokemonSpecific: false,
    sourceId: 'tcg-megacon-houston-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://tcgmegacon.com/',
    websiteUrl: 'https://tcgmegacon.com/',
  },
  {
    name: 'Midwest Card Expo Chicago March 2026',
    description: 'Regional card expo featuring sports cards, Pokemon, and other trading card games with vendors and grading services.',
    venueName: 'Donald E. Stephens Convention Center',
    address: '5555 N River Rd',
    city: 'Rosemont',
    state: 'IL',
    zipCode: '60018',
    startDate: '2026-03-14',
    endDate: '2026-03-15',
    startTime: '10:00',
    endTime: '17:00',
    admissionPrice: '$15/day',
    organizerName: 'Midwest Card Expo',
    eventType: 'card_show',
    isPokemonSpecific: false,
    sourceId: 'midwest-card-expo-chicago-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://midwestcardexpo.com/',
    websiteUrl: 'https://midwestcardexpo.com/',
  },
  {
    name: 'Ohio Card Show Columbus March 2026',
    description: 'Regional card show featuring sports cards, Pokemon, and other trading cards with early bird and general admission options.',
    venueName: 'Ohio Expo Center',
    address: '717 E 17th Ave',
    city: 'Columbus',
    state: 'OH',
    zipCode: '43211',
    startDate: '2026-03-07',
    startTime: '09:00',
    endTime: '15:00',
    admissionPrice: '$5 early bird / Free after 11am',
    organizerName: 'Ohio Card Show',
    eventType: 'card_show',
    isPokemonSpecific: false,
    sourceId: 'ohio-card-show-columbus-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://ohiocardshow.com/',
    websiteUrl: 'https://ohiocardshow.com/',
  },
  {
    name: 'SoCal Card Show Anaheim March 2026',
    description: 'Southern California card show featuring sports cards, Pokemon, and other collectible trading cards.',
    venueName: 'Anaheim Convention Center',
    address: '800 W Katella Ave',
    city: 'Anaheim',
    state: 'CA',
    zipCode: '92802',
    startDate: '2026-03-21',
    endDate: '2026-03-22',
    startTime: '10:00',
    endTime: '17:00',
    admissionPrice: '$20/day',
    organizerName: 'SoCal Card Show',
    eventType: 'card_show',
    isPokemonSpecific: false,
    sourceId: 'socal-card-show-anaheim-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://socalcardshow.com/',
    websiteUrl: 'https://socalcardshow.com/',
  },
  {
    name: 'Phoenix Card Show Spring 2026',
    description: 'Regional card show in Phoenix featuring sports cards, Pokemon, and other collectible trading cards.',
    venueName: 'Arizona State Fairgrounds',
    address: '1826 W McDowell Rd',
    city: 'Phoenix',
    state: 'AZ',
    zipCode: '85007',
    startDate: '2026-03-28',
    endDate: '2026-03-29',
    startTime: '10:00',
    endTime: '16:00',
    admissionPrice: '$10',
    organizerName: 'Phoenix Card Show',
    eventType: 'card_show',
    isPokemonSpecific: false,
    sourceId: 'phoenix-card-show-spring-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://phoenixcardshow.com/',
    websiteUrl: 'https://phoenixcardshow.com/',
  },

  // ── April 2026 Shows ─────────────────────────────────────────
  {
    name: 'PokeKon Fest Minneapolis',
    description: 'All-Pokemon trading card show touring 30+ cities. Buy, sell, and trade Pokemon cards with local collectors and vendors.',
    venueName: 'DoubleTree by Hilton Minneapolis Park Place',
    address: '1500 Park Place Blvd',
    city: 'Minneapolis',
    state: 'MN',
    zipCode: '55416',
    startDate: '2026-04-04',
    startTime: '10:00',
    endTime: '16:00',
    admissionPrice: '$20',
    organizerName: 'PokeKon',
    eventType: 'card_show',
    isPokemonSpecific: true,
    sourceId: 'pokekon-minneapolis-2026',
    sourceName: 'seed_data',
    sourceUrl: 'http://pokekon.com/',
    websiteUrl: 'http://pokekon.com/',
  },
  {
    name: 'PokeKon Fest Pittsburgh',
    description: 'All-Pokemon trading card show touring 30+ cities. Buy, sell, and trade Pokemon cards with local collectors and vendors.',
    venueName: 'DoubleTree by Hilton Pittsburgh-Green Tree',
    address: '500 Mansfield Ave',
    city: 'Pittsburgh',
    state: 'PA',
    zipCode: '15205',
    startDate: '2026-04-11',
    startTime: '10:00',
    endTime: '16:00',
    admissionPrice: '$20',
    organizerName: 'PokeKon',
    eventType: 'card_show',
    isPokemonSpecific: true,
    sourceId: 'pokekon-pittsburgh-2026',
    sourceName: 'seed_data',
    sourceUrl: 'http://pokekon.com/',
    websiteUrl: 'http://pokekon.com/',
  },
  {
    name: 'PokeKon Fest Columbus',
    description: 'All-Pokemon trading card show touring 30+ cities. Buy, sell, and trade Pokemon cards with local collectors and vendors.',
    venueName: 'DoubleTree by Hilton Columbus-Worthington',
    address: '175 Hutchinson Ave',
    city: 'Columbus',
    state: 'OH',
    zipCode: '43235',
    startDate: '2026-04-18',
    startTime: '10:00',
    endTime: '16:00',
    admissionPrice: '$20',
    organizerName: 'PokeKon',
    eventType: 'card_show',
    isPokemonSpecific: true,
    sourceId: 'pokekon-columbus-2026',
    sourceName: 'seed_data',
    sourceUrl: 'http://pokekon.com/',
    websiteUrl: 'http://pokekon.com/',
  },
  {
    name: 'PokeKon Fest Tampa',
    description: 'All-Pokemon trading card show touring 30+ cities. Buy, sell, and trade Pokemon cards with local collectors and vendors.',
    venueName: 'DoubleTree by Hilton Tampa Airport',
    address: '4500 W Cypress St',
    city: 'Tampa',
    state: 'FL',
    zipCode: '33607',
    startDate: '2026-04-25',
    startTime: '10:00',
    endTime: '16:00',
    admissionPrice: '$20',
    organizerName: 'PokeKon',
    eventType: 'card_show',
    isPokemonSpecific: true,
    sourceId: 'pokekon-tampa-2026',
    sourceName: 'seed_data',
    sourceUrl: 'http://pokekon.com/',
    websiteUrl: 'http://pokekon.com/',
  },
  {
    name: 'TCG MegaCon Charlotte 2026',
    description: 'Multi-city TCG convention tour featuring Pokemon, Yu-Gi-Oh!, Magic the Gathering, and more trading card games.',
    venueName: 'Charlotte Convention Center',
    address: '501 S College St',
    city: 'Charlotte',
    state: 'NC',
    zipCode: '28202',
    startDate: '2026-04-03',
    endDate: '2026-04-05',
    startTime: '10:00',
    endTime: '17:00',
    organizerName: 'TCG MegaCon',
    eventType: 'convention',
    isPokemonSpecific: false,
    sourceId: 'tcg-megacon-charlotte-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://tcgmegacon.com/',
    websiteUrl: 'https://tcgmegacon.com/',
  },
  {
    name: 'TCG MegaCon Atlanta 2026',
    description: 'Multi-city TCG convention tour featuring Pokemon, Yu-Gi-Oh!, Magic the Gathering, and more trading card games.',
    venueName: 'Georgia World Congress Center',
    address: '285 Andrew Young International Blvd NW',
    city: 'Atlanta',
    state: 'GA',
    zipCode: '30313',
    startDate: '2026-04-17',
    endDate: '2026-04-19',
    startTime: '10:00',
    endTime: '17:00',
    organizerName: 'TCG MegaCon',
    eventType: 'convention',
    isPokemonSpecific: false,
    sourceId: 'tcg-megacon-atlanta-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://tcgmegacon.com/',
    websiteUrl: 'https://tcgmegacon.com/',
  },
  {
    name: 'New York Card Show Spring 2026',
    description: 'Major card convention in New York City featuring sports cards, Pokemon, and other collectible trading cards.',
    venueName: 'Javits Center',
    address: '429 11th Ave',
    city: 'New York',
    state: 'NY',
    zipCode: '10001',
    startDate: '2026-04-11',
    endDate: '2026-04-12',
    startTime: '10:00',
    endTime: '18:00',
    admissionPrice: '$25/day',
    organizerName: 'New York Card Show',
    eventType: 'convention',
    isPokemonSpecific: false,
    sourceId: 'ny-card-show-spring-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://nycardshow.com/',
    websiteUrl: 'https://nycardshow.com/',
  },
  {
    name: 'Seattle Card Show Spring 2026',
    description: 'Regional card show in the Pacific Northwest featuring sports cards, Pokemon, and other collectible trading cards.',
    venueName: 'Greater Tacoma Convention Center',
    address: '1500 Commerce St',
    city: 'Tacoma',
    state: 'WA',
    zipCode: '98402',
    startDate: '2026-04-18',
    endDate: '2026-04-19',
    startTime: '10:00',
    endTime: '17:00',
    admissionPrice: '$15/day',
    organizerName: 'Seattle Card Show',
    eventType: 'card_show',
    isPokemonSpecific: false,
    sourceId: 'seattle-card-show-spring-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://seattlecardshow.com/',
    websiteUrl: 'https://seattlecardshow.com/',
  },
  {
    name: 'Portland Card Show Spring 2026',
    description: 'Regional card show in the Pacific Northwest featuring sports cards, Pokemon, and other collectible trading cards.',
    venueName: 'Oregon Convention Center',
    address: '777 NE Martin Luther King Jr Blvd',
    city: 'Portland',
    state: 'OR',
    zipCode: '97232',
    startDate: '2026-04-25',
    endDate: '2026-04-26',
    startTime: '10:00',
    endTime: '17:00',
    admissionPrice: '$10/day',
    organizerName: 'Portland Card Show',
    eventType: 'card_show',
    isPokemonSpecific: false,
    sourceId: 'portland-card-show-spring-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://portlandcardshow.com/',
    websiteUrl: 'https://portlandcardshow.com/',
  },
  {
    name: 'Las Vegas Card Convention April 2026',
    description: 'Major card convention in Las Vegas featuring sports cards, Pokemon, and other collectible trading cards.',
    venueName: 'Las Vegas Convention Center',
    address: '3150 Paradise Rd',
    city: 'Las Vegas',
    state: 'NV',
    zipCode: '89109',
    startDate: '2026-04-10',
    endDate: '2026-04-12',
    startTime: '10:00',
    endTime: '18:00',
    admissionPrice: '$20/day',
    organizerName: 'Las Vegas Card Convention',
    eventType: 'convention',
    isPokemonSpecific: false,
    sourceId: 'lv-card-convention-2026',
    sourceName: 'seed_data',
    sourceUrl: 'https://lasvegascardconvention.com/',
    websiteUrl: 'https://lasvegascardconvention.com/',
  },
];

export class SeedScraper extends BaseScraper {
  readonly sourceName = 'seed_data';

  async scrape(): Promise<ScrapedShow[]> {
    console.log('[seed_data] Loading verified card show seed data...');

    const validated: ScrapedShow[] = [];
    for (const event of SEED_EVENTS) {
      const result = scrapedShowSchema.safeParse(event);
      if (result.success) {
        validated.push(result.data);
      } else {
        console.warn(`[seed_data] Validation failed for "${event.name}":`, result.error.format());
      }
    }

    console.log(`[seed_data] Loaded ${validated.length} verified events`);
    return validated;
  }
}
